spring.application.name=fynxt-order-booking

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/fynxt_order_booking
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# SQL Schema
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql